[package]
name = "rust-ab"
version = "0.5.0"
authors = ["Carmine Spagnuolo <spagnuolocarmine@gmail.com>", "Alessia Antelmi <aantelmi@unisa.it>", "Matteo D'Auria <matdauria@unisa.it>", "Daniele De Vinco <danieledevinco1996@gmail.com", "Francesco Foglia <frafonia@gmail.com>", "Pasquale Caramante <pasqcaramante@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["discrete", "simulation", "agent based model", "agent based simulation"]
categories = ["science", "simulation", "agent based model"]
readme = "README.md"
homepage = "https://github.com/spagnuolocarmine/rust-ab"
repository = "https://github.com/spagnuolocarmine/rust-ab"

[dependencies]
hashbrown = "0.3"
priority-queue = "0.5.4"
criterion =  "0.3.3"
rand = "0.6.5"
lazy_static = "1.3.0"
cfg-if = "1.0.0"
num_cpus = "1.13.0"
rayon="1.5.0"
clap="2.33.3"
ahash="0.6.2"

[[bench]]
name = "scaling"
harness = false

[[bench]]
name = "constant_field"
harness = false

[[bench]]
name = "constant_density"
harness = false

[[bench]]
name = "constant_agent"
harness = false

# Must be kept separate and asked to the user due to missing support for conditional compilation of features
# https://github.com/rust-lang/cargo/issues/7914
[features]
amethyst_metal = ["amethyst", "amethyst/metal"]
amethyst_vulkan = ["amethyst", "amethyst/vulkan"]
parallel = []

[dependencies.amethyst]
version = "0.15.3"
optional = true
default-features = false
features = ["renderer"]

[[example]]
name = "antsforaging"
path = "examples/antsforaging/antsforaging/main.rs"

[[example]]
name = "antsforaging_ui"
path = "examples/antsforaging/antsforaging_ui/main.rs"

[[example]]
name = "boids"
path = "examples/boids/boids.rs"

[[example]]
name = "boids_ui"
path = "examples/boids/boids_ui/main.rs"